GET http://localhost:5000/merns

###

GET http://localhost:5000/merns/64ba38fa38a81137345e1329

###

POST http://localhost:5000/merns
Content-Type: application/json

{
    "name": "CrazyMeowl123",
    "activeState": "Idk"
}

###

PATCH  http://localhost:5000/merns/64ba38fa38a81137345e1329
Content-Type: application/json

{
    "name": "No more CrazyMeowl",
    "activeState": "false"
}


###

DELETE http://localhost:5000/merns/64ba38fa38a81137345e1329


